name: N1 Generate diffconfig

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  diff:
    runs-on: ubuntu-24.04

    steps:
    - name: 检出源码
      uses: actions/checkout@main

    - name: 初始化环境
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git
        sudo timedatectl set-timezone "$TZ"
        mkdir -p /workdir/diff

    - name: 克隆 OpenWrt 源码
      working-directory: /workdir
      run: git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 openwrt

    - name: SSH 上传 diffconfig
      uses: P3TERX/ssh2actions@main
      if: github.event.inputs.ssh == 'true'
      with:
        # 配置 SSH host、user、key 等，上传 diffconfig 到 /workdir/diff/.config

    - name: 生成差异文件
      run: |
        cp /workdir/diff/.config /workdir/openwrt/.config
        cd /workdir/openwrt
        make defconfig
        scripts/diffconfig.sh > /workdir/diff/diffconfig.txt
        ls -l /workdir/diff/

    - name: 发布到 GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: diffconfig_$(date +'%Y%m%d')
        files: /workdir/diff/diffconfig.txt
        token: ${{ env.GITHUB_TOKEN }}

    - name: 发送到 Telegram
      if: env.TELEGRAM_TOKEN != ''
      run: |
        DIFF_FILE=/workdir/diff/diffconfig.txt
        curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ env.TELEGRAM_CHAT_ID }}" \
          -d text="🎉 diffconfig 已生成并上传到 GitHub Release"
        curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendDocument" \
          -F chat_id="${{ env.TELEGRAM_CHAT_ID }}" \
          -F document=@"$DIFF_FILE" \
          -F caption="diffconfig 文件"
