name: OpenWrt Build with SSH Config

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: my_diffconfig.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y tmate curl jq git

      - name: 克隆 OpenWrt 源码
        run: |
          git clone --depth=1 -b $REPO_BRANCH $REPO_URL openwrt
          cd openwrt

      - name: 启动 SSH 终端（手动配置）
        run: |
          echo "请使用 SSH 连接 GitHub Actions 运行环境，并执行 make menuconfig 配置 OpenWrt"
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          sleep 3600  # 保持 Runner 运行 1 小时，等待手动配置

      - name: 生成 diffconfig
        run: |
          cd openwrt
          ./scripts/diffconfig.sh > $CONFIG_FILE

      - name: 提交 diffconfig 到 GitHub
        run: |
          cd openwrt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add $CONFIG_FILE
          git commit -m "手动选择后更新 diffconfig"
          git push || echo "没有新的 diffconfig 变更"
