name: Test OpenWrt Packit with wildcard path

on: workflow_dispatch

jobs:
  test-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check firmware files
        run: ls -lh openwrt/bin/targets/*/*/*.tar.gz || echo "No firmware files found"

      - name: Fake compile success
        run: echo "compile_status=success" >> $GITHUB_ENV

      - name: Package OpenWrt ARMVirt
        if: ${{ env.compile_status }} == 'success' && !cancelled()
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
          KERNEL_REPO_URL: ophub/kernel
          KERNEL_VERSION_NAME: 6.6.y
          KERNEL_AUTO_LATEST: true
          PACKAGE_SOC: s905d
          GZIP_IMGS: .xz
          SCRIPT_DIY_PATH: N1/mk_s905d_n1.sh
          WHOAMI: xyself
          OPENWRT_VER: "2025.07.03"
          SW_FLOWOFFLOAD: 0
          SFE_FLOW: 0
